blank_issues_enabled: true
contact_links:
  - name: Support (on Discord)
    url: https://universal-team.net/discord
    about: "Please use #support on the Discord server to for support-related questions"
